### ISSUE TITLE
what about using mode=valid in conv2D?

### ISSUE THREAD

**Issue by alyato** [jacobzweig/Keras-RCNN#1]
hi @jacobzweig  Thanks for you share this code.
But i check that you use the `mode=sum` in `merge`

> stack5 = merge([stack1, stack4], mode='sum')

But what if the output_shapes in stack1 and stack4 are difference because of `borde_mode=valid,not same` in `conv2D`, i need to use the `Reshape`. 
Is it right? thanks

**Comment by jacobzweig** [comment]
Hi, yep, you'd need to reshape there before summing the layers together.
